### ISSUE TITLE
Scroll bar displayed on "Numbers" button container. Firefox 29 on Mint 16 64bit

### ISSUE THREAD

**Issue by chrishirst** [mar-kolya/secure-password-generator#1] opened 2014-05-15 10:49 UTC
When activated from toolbar icon.

Screen shot.

![sec-pw-gen](https://cloud.githubusercontent.com/assets/3680285/2983094/e5a53b0a-dc1d-11e3-8d73-bfa10907300a.png)

**Comment by mar-kolya** [comment] 2015-01-17 00:55
How were you able to actually add that button to navbar? I do not think this pluging provides that ability.

**Comment by chrishirst** [comment] 2015-01-17 13:23
So you don't know how to "customise" the FireFox toolbars and position toolbars,  icons and buttons wherever you actually want them?
Just to note; it is not actually 'on' the navigation bar, the button is simply positioned **alongside** the navigation bar on the same 'toolbar' as AdBlock plus and the pwgen extension buttons are.

**Comment by chrishirst** [comment] 2015-01-17 13:31
Oh and to add:

It matters not where I position the button/toolbar within the browser toolbar area, the effect is the same so the problem is not congruent with being on the 'edge' of the browser window.

**Comment by mar-kolya** [comment] 2015-01-17 15:17
I'm not sure comments in this kind of tone are helpful in any way.

In current firefox nightly (and before that) this plugin doesn't produce a button in 'customize' tab. So as far as I can see there is no way to put a button on toolbar.

**Comment by chrishirst** [comment] 2015-01-18 18:05
No 'tone' to it, it's a simple question. Surely the simple fact that I **HAVE** the button positioned there demonstrates that it is possible?

And how is that relevant to the "Numbers" button container being to small for the text in it, thus displaying a scroll bar.

**Comment by mar-kolya** [comment] 2015-01-18 18:15
Well, knowing how to do that would have helped someone to reproduce the problem and investigate that.

OTOH looking at your screen shot I might be able to guess that you may be using some other addon unrelated to this one.

You may want to try this addon: https://addons.mozilla.org/en-US/firefox/addon/secure-password-generator/?src=search if you prefer. Works fine for me.

As such I'm going to close this issue since there are no steps to reproduce and it looks like it is about some other (maybe unsupported) project.

**Closed by mar-kolya** 2015-01-18 18:15 UTC
